In [2]:
import pandas as pd
import numpy as np
import pickle

In [3]:
dataset=pd.read_csv('train.csv')

In [4]:
dataset.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
dataset=dataset.dropna()
dataset=dataset.reset_index()

In [6]:
X=dataset.iloc[:,0:5]
y=dataset.iloc[:,-1]

In [7]:
X

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [8]:
df_copy=X.copy()

In [9]:
df_copy.head().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   5 non-null      int64 
 1   id      5 non-null      int64 
 2   title   5 non-null      object
 3   author  5 non-null      object
 4   text    5 non-null      object
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes


In [10]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,18285):
    review=re.sub('[^A-Za-z]',' ',df_copy['title'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [11]:
corpus[:20]

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,ngram_range=(1,3))
X=cv.fit_transform(corpus).toarray()

In [13]:
X.shape

(18285, 5000)

In [14]:
pickle.dump(cv,open('transform.pkl','wb'))

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [16]:
cv.get_feature_names()

['abandon',
 'abc',
 'abc news',
 'abduct',
 'abe',
 'abedin',
 'abl',
 'abort',
 'abroad',
 'absolut',
 'abstain',
 'absurd',
 'abus',
 'abus new',
 'abus new york',
 'academi',
 'accept',
 'access',
 'access pipelin',
 'access pipelin protest',
 'accid',
 'accident',
 'accord',
 'account',
 'accus',
 'achiev',
 'acknowledg',
 'acknowledg emf',
 'acknowledg emf damag',
 'acquit',
 'acquitt',
 'across',
 'act',
 'act like',
 'act new',
 'act new york',
 'action',
 'activ',
 'activist',
 'actor',
 'actual',
 'ad',
 'adam',
 'add',
 'addict',
 'address',
 'adhd',
 'admin',
 'administr',
 'admir',
 'admit',
 'adopt',
 'adult',
 'advanc',
 'advertis',
 'advic',
 'advis',
 'advis new',
 'advis new york',
 'advisor',
 'advoc',
 'affair',
 'affect',
 'affili',
 'affirm',
 'afford',
 'afford care',
 'afford care act',
 'afghan',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'african american',
 'aftermath',
 'ag',
 'age',
 'age new',
 'age new york',
 'agenc',
 'agenda',
 'agenda breitbar

In [17]:
count_df=pd.DataFrame(X_train,columns=cv.get_feature_names())

In [18]:
count_df.head()

abandon  abc  abc news  abduct  abe  abedin  abl  abort  abroad  absolut  \
0        0    0         0       0    0       0    0      0       0        0   
1        0    0         0       0    0       0    0      0       0        0   
2        0    0         0       0    0       0    0      0       0        0   
3        0    0         0       0    0       0    0      0       0        0   
4        0    0         0       0    0       0    0      0       0        0   

   ...  zero  zika  zika viru  zionist  zone  zone new  zone new york  zoo  \
0  ...     0     0          0        0     0         0              0    0   
1  ...     0     0          0        0     0         0              0    0   
2  ...     0     0          0        0     0         0              0    0   
3  ...     0     0          0        0     0         0              0    0   
4  ...     0     0          0        0     0         0              0    0   

   zu  zuckerberg  
0   0           0  
1   0           0  
2   0           0  
3   0           0  
4   0           0  

[5 rows x 5000 columns]

In [19]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier=classifier.fit(X_train,y_train)

In [25]:
filename='classifier.pkl'
pickle.dump(classifier,open(filename,'wb'))

In [26]:
y_pred=classifier.predict(X_test)

In [27]:
y_pred

array([1, 1, 1, ..., 0, 0, 1])

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
score=accuracy_score(y_test,y_pred)*100
print(score)

90.07383100902379


In [29]:
cm=confusion_matrix(y_test,y_pred)

In [30]:
cm

array([[1825,  215],
       [ 148, 1469]])

In [23]:
#test=pd.read_csv('test.csv')
#submit=pd.read_csv('submit.csv')
#df_test=pd.merge(test,submit)
#df_test

id                                              title  \
0     20800  Specter of Trump Loosens Tongues, if Not Purse...   
1     20801  Russian warships ready to strike terrorists ne...   
2     20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3     20803  Tim Tebow Will Attempt Another Comeback, This ...   
4     20804                    Keiser Report: Meme Wars (E995)   
...     ...                                                ...   
5195  25995  The Bangladeshi Traffic Jam That Never Ends - ...   
5196  25996  John Kasich Signs One Abortion Bill in Ohio bu...   
5197  25997  California Today: What, Exactly, Is in Your Su...   
5198  25998  300 US Marines To Be Deployed To Russian Borde...   
5199  25999  Awkward Sex, Onscreen and Off - The New York T...   

                       author  \
0            David Streitfeld   
1                         NaN   
2               Common Dreams   
3               Daniel Victor   
4     Truth Broadcast Network   
...                       ...   
5195               Jody Rosen   
5196      Sheryl Gay Stolberg   
5197             Mike McPhate   
5198                      NaN   
5199              Teddy Wayne   

                                                   text  label  
0     PALO ALTO, Calif.  —   After years of scorning...      0  
1     Russian warships ready to strike terrorists ne...      1  
2     Videos #NoDAPL: Native American Leaders Vow to...      0  
3     If at first you don’t succeed, try a different...      1  
4     42 mins ago 1 Views 0 Comments 0 Likes 'For th...      1  
...                                                 ...    ...  
5195  Of all the dysfunctions that plague the world’...      0  
5196  WASHINGTON  —   Gov. John Kasich of Ohio on Tu...      1  
5197  Good morning. (Want to get California Today by...      0  
5198  « Previous - Next » 300 US Marines To Be Deplo...      1  
5199  Perhaps you’ve seen the new TV series whose pi...      0  

[5200 rows x 5 columns]

In [24]:
#df_test=df_test.dropna()
#df_test=df_test.reset_index()

In [25]:
#X_test=df_test.iloc[:,0:4]
#real_val=df_test.iloc[:,-1]

In [26]:
#real_val

0       0
1       0
2       1
3       1
4       1
       ..
4570    1
4571    0
4572    1
4573    0
4574    0
Name: label, Length: 4575, dtype: int64

In [27]:
#X_test

index     id                                              title  \
0         0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1         2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
2         3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
3         4  20804                    Keiser Report: Meme Wars (E995)   
4         6  20806  Pelosi Calls for FBI Investigation to Find Out...   
...     ...    ...                                                ...   
4570   5194  25994  Trump on If ’Tapes’ Exist of Comey Conversatio...   
4571   5195  25995  The Bangladeshi Traffic Jam That Never Ends - ...   
4572   5196  25996  John Kasich Signs One Abortion Bill in Ohio bu...   
4573   5197  25997  California Today: What, Exactly, Is in Your Su...   
4574   5199  25999  Awkward Sex, Onscreen and Off - The New York T...   

                       author  
0            David Streitfeld  
1               Common Dreams  
2               Daniel Victor  
3     Truth Broadcast Network  
4                     Pam Key  
...                       ...  
4570                  Pam Key  
4571               Jody Rosen  
4572      Sheryl Gay Stolberg  
4573             Mike McPhate  
4574              Teddy Wayne  

[4575 rows x 4 columns]

In [28]:
#corpus_test=[]
#for x in range(0,4575):
#    review=re.sub('[^a-zA-Z]',' ',X_test['title'][x])
#    review=review.lower()
#    review=review.split()
#    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
#    review=' '.join(review)
#    corpus_test.append(review)  

In [29]:
#cm_test=CountVectorizer(max_features=5000)
#X_test=cm_test.fit_transform(corpus_test).toarray()

In [113]:
#X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
#test_pred=classifier.predict(X_test)

In [31]:
#cm_test=confusion_matrix(real_val,test_pred)

In [32]:
#cm_test

array([[ 655, 1558],
       [ 778, 1584]])

In [34]:
#score_test=accuracy_score(real_val,test_pred)*100

In [35]:
#score

90.07383100902379